// <auto-generated />
using AddressManager.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AddressManager.Domain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261006090326_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AddressManager.Domain.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApartmentNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApartmentNumber = "10",
                            CityId = 1,
                            HouseNumber = "1",
                            PostalCode = "01001",
                            Street = "вул. Хрещатик"
                        },
                        new
                        {
                            Id = 2,
                            ApartmentNumber = "45",
                            CityId = 1,
                            HouseNumber = "3",
                            PostalCode = "01004",
                            Street = "вул. Велика Васильківська"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            HouseNumber = "12",
                            PostalCode = "07400",
                            Street = "вул. Бориспільська"
                        },
                        new
                        {
                            Id = 4,
                            ApartmentNumber = "2",
                            CityId = 3,
                            HouseNumber = "7",
                            PostalCode = "79000",
                            Street = "вул. Шевченка"
                        },
                        new
                        {
                            Id = 5,
                            ApartmentNumber = "8",
                            CityId = 3,
                            HouseNumber = "15",
                            PostalCode = "79008",
                            Street = "просп. Свободи"
                        },
                        new
                        {
                            Id = 6,
                            ApartmentNumber = "5",
                            CityId = 4,
                            HouseNumber = "22",
                            PostalCode = "65026",
                            Street = "вул. Дерибасівська"
                        },
                        new
                        {
                            Id = 7,
                            ApartmentNumber = "12",
                            CityId = 5,
                            HouseNumber = "100",
                            PostalCode = "00-026",
                            Street = "ul. Marszałkowska"
                        },
                        new
                        {
                            Id = 8,
                            CityId = 5,
                            HouseNumber = "64",
                            PostalCode = "00-357",
                            Street = "ul. Nowy Świat"
                        },
                        new
                        {
                            Id = 9,
                            ApartmentNumber = "1",
                            CityId = 6,
                            HouseNumber = "3",
                            PostalCode = "31-019",
                            Street = "ul. Floriańska"
                        },
                        new
                        {
                            Id = 10,
                            CityId = 7,
                            HouseNumber = "12",
                            PostalCode = "80539",
                            Street = "Maximilianstraße"
                        });
                });

            modelBuilder.Entity("AddressManager.Domain.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Киев",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Бровары",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Львов",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Одесса",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 5,
                            Name = "Варшава",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 6,
                            Name = "Краков",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 7,
                            Name = "Мюнхен",
                            RegionId = 6
                        });
                });

            modelBuilder.Entity("AddressManager.Domain.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "UA",
                            Name = "Украина"
                        },
                        new
                        {
                            Id = 2,
                            Code = "PL",
                            Name = "Польша"
                        },
                        new
                        {
                            Id = 3,
                            Code = "DE",
                            Name = "Германия"
                        });
                });

            modelBuilder.Entity("AddressManager.Domain.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Киевская область"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "Львовская область"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            Name = "Одесская область"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 2,
                            Name = "Мазовецкое воеводство"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 2,
                            Name = "Малопольское воеводство"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 3,
                            Name = "Бавария"
                        });
                });

            modelBuilder.Entity("AddressManager.Domain.Models.Address", b =>
                {
                    b.HasOne("AddressManager.Domain.Models.City", "City")
                        .WithMany("Addresses")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("AddressManager.Domain.Models.City", b =>
                {
                    b.HasOne("AddressManager.Domain.Models.Region", "Region")
                        .WithMany("Cities")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("AddressManager.Domain.Models.Region", b =>
                {
                    b.HasOne("AddressManager.Domain.Models.Country", "Country")
                        .WithMany("Regions")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("AddressManager.Domain.Models.City", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("AddressManager.Domain.Models.Country", b =>
                {
                    b.Navigation("Regions");
                });

            modelBuilder.Entity("AddressManager.Domain.Models.Region", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}


